/*
 * Form.java
 *
 * Created on 16 de abril de 2008, 20:30
 */

package buenetxea.gui.panelak;
import java.awt.ComponentOrientation;
import java.awt.Insets;

import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;

/**
 *
 * @author  Torwidev
 */
public class DatosInmueblePanel extends javax.swing.JPanel {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form Form */
    public DatosInmueblePanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel6.setBorder(new EmptyBorder(0, 0, 0, 0));
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox1.setMargin(new Insets(2, 0, 2, 2));
        jCheckBox1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jTextField6 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel7.setBorder(new EmptyBorder(0, 0, 0, 0));
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox2.setMargin(new Insets(2, 0, 2, 2));
        jCheckBox2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jPanel8 = new javax.swing.JPanel();
        jPanel8.setBorder(new EmptyBorder(0, 0, 0, 0));
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox3.setMargin(new Insets(2, 0, 2, 2));
        jCheckBox3.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBorder(new TitledBorder(new EmptyBorder(0, 0, 0, 0), "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        jPanel1.setBorder(new TitledBorder(null, "Peritaje", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        jLabel20.setText("Perito");


        jLabel21.setText("Fecha");


        jLabel22.setText("Hora");


        jRadioButton1.setText("Piso");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Casa");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Local");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("Parking");

        jPanel2.setBorder(new TitledBorder(null, "Localización", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        jLabel23.setText("Referencia");


        jLabel24.setText("Zona");

        jLabel25.setText("Dirección");



        jPanel3.setBorder(new TitledBorder(null, "Descripción", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tipo", "m2", "Descripción"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tipo", "m2", "Descripción"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel4.setBorder(new TitledBorder(null, "General", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        jLabel1.setText("m2 constr.");


        jLabel2.setText("Gas");

        jLabel3.setText("Luminoso");

        jLabel4.setText("Techos");

        jLabel5.setText("Exterior");

        jLabel6.setText("Años Finca");

        jLabel7.setText("Portero");

        jCheckBox1.setText("Ascensor");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });






        jLabel8.setText("m2 útiles");

        jLabel9.setText("Calefacción");

        jLabel10.setText("Pintura");

        jLabel11.setText("Tipo suelo");



        jLabel12.setText("Orientación");



        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBox2.setText("Desalojo");

        jLabel13.setText("m2 parcela");

        jLabel14.setText("Puertas");

        jLabel15.setText("Ventanas");

        jLabel16.setText("Muebles");

        jLabel17.setText("Altura edif. (pisos)");

        jLabel18.setText("Alt. real piso (piso)");

        jLabel19.setText("Gastos comun.");

        jCheckBox3.setText("Reformas");








        jPanel5.setBorder(new TitledBorder(null, "Observaciones", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8Layout.setHorizontalGroup(
        	jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addGroup(jPanel8Layout.createSequentialGroup()
		        	.addContainerGap()
		        	.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
			        	.addGroup(jPanel8Layout.createSequentialGroup()
				        	.addComponent(jCheckBox3)
				        	.addGap(4, 4, 4))
			        	.addGroup(jPanel8Layout.createSequentialGroup()
				        	.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
					        	.addComponent(jLabel18)
					        	.addComponent(jLabel19))
				        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				        	.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
					        	.addComponent(jTextField17, GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
					        	.addComponent(jTextField16, GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)))
			        	.addGroup(jPanel8Layout.createSequentialGroup()
				        	.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
					        	.addComponent(jLabel17)
					        	.addComponent(jLabel16)
					        	.addComponent(jLabel15)
					        	.addComponent(jLabel14)
					        	.addComponent(jLabel13))
				        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				        	.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
					        	.addComponent(jTextField11, GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
					        	.addComponent(jTextField12, GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
					        	.addComponent(jTextField13, GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
					        	.addComponent(jTextField14, GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
					        	.addComponent(jTextField15, GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE))
				        	.addGap(1, 1, 1)))
		        	.addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
        	jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addGroup(jPanel8Layout.createSequentialGroup()
		        	.addContainerGap()
		        	.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel13)
			        	.addComponent(jTextField11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel14)
			        	.addComponent(jTextField12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel15)
			        	.addComponent(jTextField13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel16)
			        	.addComponent(jTextField14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel17)
			        	.addComponent(jTextField15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel18)
			        	.addComponent(jTextField16, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel19)
			        	.addComponent(jTextField17, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addComponent(jCheckBox3)
		        	.addContainerGap())
        );
        jPanel8.setLayout(jPanel8Layout);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7Layout.setHorizontalGroup(
        	jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addGroup(jPanel7Layout.createSequentialGroup()
		        	.addContainerGap()
		        	.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
			        	.addComponent(jCheckBox2)
			        	.addGroup(jPanel7Layout.createSequentialGroup()
				        	.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
					        	.addComponent(jLabel12)
					        	.addComponent(jLabel11)
					        	.addComponent(jLabel10)
					        	.addComponent(jLabel9)
					        	.addComponent(jLabel8))
				        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				        	.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
					        	.addComponent(jTextField7, GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
					        	.addComponent(jTextField8, GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
					        	.addComponent(jTextField9, GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
					        	.addComponent(jTextField10, GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
					        	.addComponent(jComboBox1, 0, 6, Short.MAX_VALUE))))
		        	.addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
        	jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addGroup(jPanel7Layout.createSequentialGroup()
		        	.addContainerGap()
		        	.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel8)
			        	.addComponent(jTextField7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel9)
			        	.addComponent(jTextField8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel10)
			        	.addComponent(jTextField9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel11)
			        	.addComponent(jTextField10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel12)
			        	.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addComponent(jCheckBox2)
		        	.addGap(59, 59, 59))
        );
        jPanel7.setLayout(jPanel7Layout);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6Layout.setHorizontalGroup(
        	jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addGroup(jPanel6Layout.createSequentialGroup()
		        	.addContainerGap()
		        	.addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
			        	.addGroup(jPanel6Layout.createSequentialGroup()
				        	.addComponent(jLabel6)
				        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				        	.addComponent(jSpinner1, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE))
			        	.addGroup(jPanel6Layout.createSequentialGroup()
				        	.addComponent(jLabel7)
				        	.addGap(20, 20, 20)
				        	.addComponent(jTextField6, GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
			        	.addComponent(jCheckBox1)
			        	.addGroup(jPanel6Layout.createSequentialGroup()
				        	.addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
					        	.addComponent(jLabel2)
					        	.addComponent(jLabel3)
					        	.addComponent(jLabel5)
					        	.addComponent(jLabel4)
					        	.addComponent(jLabel1))
				        	.addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
					        	.addGroup(jPanel6Layout.createSequentialGroup()
						        	.addGap(5, 5, 5)
						        	.addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
							        	.addGroup(GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
								        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
								        	.addComponent(jTextField2))
							        	.addComponent(jTextField3, GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
							        	.addComponent(jTextField4, GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
							        	.addComponent(jTextField5, GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
					        	.addGroup(jPanel6Layout.createSequentialGroup()
						        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
						        	.addComponent(jTextField1, GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)))))
		        	.addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
        	jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addGroup(jPanel6Layout.createSequentialGroup()
		        	.addContainerGap()
		        	.addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel1)
			        	.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel2)
			        	.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel3)
			        	.addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel4)
			        	.addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel5)
			        	.addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel6)
			        	.addComponent(jSpinner1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel7)
			        	.addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addComponent(jCheckBox1))
        );
        jPanel6.setLayout(jPanel6Layout);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addGroup(jPanel2Layout.createSequentialGroup()
		        	.addContainerGap()
		        	.addComponent(jLabel23)
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addComponent(jTextField21, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
		        	.addGap(12, 12, 12)
		        	.addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
			        	.addGroup(jPanel2Layout.createSequentialGroup()
				        	.addComponent(jLabel25)
				        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				        	.addComponent(jTextField23, GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
			        	.addGroup(jPanel2Layout.createSequentialGroup()
				        	.addComponent(jLabel24)
				        	.addGap(23, 23, 23)
				        	.addComponent(jTextField22, GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)))
		        	.addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addGroup(jPanel2Layout.createSequentialGroup()
		        	.addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel23)
			        	.addComponent(jLabel24)
			        	.addComponent(jTextField22, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
			        	.addComponent(jTextField21, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			        	.addComponent(jLabel25)
			        	.addComponent(jTextField23, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		        	.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4Layout.setHorizontalGroup(
        	jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addGroup(jPanel4Layout.createSequentialGroup()
		        	.addComponent(jPanel6, GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addComponent(jPanel7, GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addComponent(jPanel8, GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
		        	.addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
        	jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addGroup(jPanel4Layout.createSequentialGroup()
		        	.addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
			        	.addComponent(jPanel8, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
			        	.addComponent(jPanel7, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
			        	.addComponent(jPanel6, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
		        	.addGap(3, 3, 3))
        );
        jPanel4.setLayout(jPanel4Layout);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5Layout.setHorizontalGroup(
        	jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addGroup(jPanel5Layout.createSequentialGroup()
		        	.addContainerGap()
		        	.addComponent(jScrollPane3, GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
		        	.addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
        	jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addComponent(jScrollPane3, GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );
        jPanel5.setLayout(jPanel5Layout);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addGroup(jPanel1Layout.createSequentialGroup()
		        	.addContainerGap()
		        	.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
			        	.addGroup(jPanel1Layout.createSequentialGroup()
				        	.addComponent(jLabel20)
				        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				        	.addComponent(jTextField18, GroupLayout.PREFERRED_SIZE, 268, GroupLayout.PREFERRED_SIZE))
			        	.addGroup(jPanel1Layout.createSequentialGroup()
				        	.addComponent(jLabel21)
				        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				        	.addComponent(jTextField19, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
				        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				        	.addComponent(jLabel22)
				        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				        	.addComponent(jTextField20, GroupLayout.PREFERRED_SIZE, 99, GroupLayout.PREFERRED_SIZE)))
		        	.addGap(52, 52, 52)
		        	.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
			        	.addGroup(jPanel1Layout.createSequentialGroup()
				        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				        	.addComponent(jRadioButton2))
			        	.addComponent(jRadioButton1))
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
			        	.addComponent(jRadioButton3)
			        	.addComponent(jRadioButton4))
		        	.addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addGroup(jPanel1Layout.createSequentialGroup()
		        	.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
			        	.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
				        	.addComponent(jRadioButton4)
				        	.addComponent(jRadioButton2))
			        	.addGroup(jPanel1Layout.createSequentialGroup()
				        	.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
					        	.addComponent(jLabel20)
					        	.addComponent(jTextField18, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					        	.addComponent(jRadioButton1)
					        	.addComponent(jRadioButton3))
				        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				        	.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
					        	.addComponent(jLabel21)
					        	.addComponent(jTextField19, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					        	.addComponent(jTextField20, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					        	.addComponent(jLabel22))))
		        	.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addGroup(jPanel3Layout.createSequentialGroup()
		        	.addContainerGap()
		        	.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
		        	.addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
	        	.addGroup(jPanel3Layout.createSequentialGroup()
		        	.addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
			        	.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
			        	.addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE))
		        	.addContainerGap())
        );
        jPanel3.setLayout(jPanel3Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
	        	.addGroup(layout.createSequentialGroup()
		        	.addContainerGap()
		        	.addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
			        	.addComponent(jPanel5, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
			        	.addComponent(jPanel2, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
			        	.addComponent(jPanel1, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
			        	.addComponent(jPanel3, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
			        	.addComponent(jPanel4, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
		        	.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(GroupLayout.Alignment.LEADING)
	        	.addGroup(layout.createSequentialGroup()
		        	.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
		        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		        	.addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
		        	.addContainerGap())
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
    
}
