/*
 * Form.java
 *
 * Created on 16 de abril de 2008, 20:30
 */

package buenetxea.gui.panelak;

import java.io.IOException;
import java.sql.SQLException;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.LayoutStyle;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;

import buenetxea.gui.panelak.azpipanelak.DatosInmueblePanel;
import buenetxea.kudeatzaileak.Kudeatzailea;
import buenetxea.objektuak.Inmueble;
import buenetxea.objektuak.Peritaje;

public class ModificarInmueblePanel extends javax.swing.JPanel {
	// private Inmueble etxea;
	// private Peritaje peritajeInm;
	private DatosInmueblePanel datosInmueblePanel;
	private JButton modificarButton;
	// private int erreferentzia;
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Kudeatzailea kud;

	/**
	 * Creates new form Form
	 * 
	 * @throws ClassNotFoundException
	 * @throws SQLException
	 */
	public ModificarInmueblePanel(int erref) throws SQLException,
			ClassNotFoundException {
		// InmuebleKud InmuebleKudeatzailea = InmuebleKud.getInstance();
		// PeritajeKud PeritajeKudeatzailea = PeritajeKud.getInstance();
		// this.erreferentzia = erref;

		try {
			kud = Kudeatzailea.getInstance();

			initComponents(erref);

			modificarButton = new JButton();
			modificarButton.setText("Modificar Inmueble");

			datosInmueblePanel = new DatosInmueblePanel();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * 
	 * @throws ClassNotFoundException
	 * @throws SQLException
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents(int erreferentzia) {
		try {
			Inmueble etxea = kud.getInmueble(erreferentzia);
			Peritaje peritajeInm = kud.getUltimoPeritaje(erreferentzia);

			setBorder(new TitledBorder(new EmptyBorder(0, 0, 0, 0), "",
					TitledBorder.DEFAULT_JUSTIFICATION,
					TitledBorder.DEFAULT_POSITION, null, null));

			javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
			layout
					.setHorizontalGroup(layout
							.createParallelGroup(GroupLayout.Alignment.TRAILING)
							.addGroup(
									layout
											.createSequentialGroup()
											.addContainerGap()
											.addGroup(
													layout
															.createParallelGroup(
																	GroupLayout.Alignment.LEADING)
															.addComponent(
																	modificarButton,
																	GroupLayout.Alignment.TRAILING)
															.addComponent(
																	datosInmueblePanel,
																	GroupLayout.DEFAULT_SIZE,
																	643,
																	Short.MAX_VALUE))
											.addContainerGap()));
			layout.setVerticalGroup(layout.createParallelGroup(
					GroupLayout.Alignment.LEADING).addGroup(
					GroupLayout.Alignment.TRAILING,
					layout.createSequentialGroup().addContainerGap()
							.addComponent(datosInmueblePanel,
									GroupLayout.DEFAULT_SIZE, 662,
									Short.MAX_VALUE).addPreferredGap(
									LayoutStyle.ComponentPlacement.RELATED)
							.addComponent(modificarButton).addContainerGap()));
			this.setLayout(layout);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
